version: 2.1

orbs:
  orb-tools: circleci/orb-tools@2
  elixir: coletiv/elixir@dev:master
workflows:
  btd:
    jobs:
      - orb-tools/pack:
          source-dir: src/
          destination-orb-path: packed/orb.yml
          workspace-path: packed/orb.yml
          artifact-path: packed/orb.yml

      - orb-tools/publish:
          orb-path: packed/orb.yml
          orb-ref: "coletiv/elixir@dev:${CIRCLE_BRANCH}"
          publish-token-variable: "$CIRCLECI_API_TOKEN"
          attach-workspace: true
          checkout: false
          requires: [orb-tools/pack]

      - elixir/build-and-test:
          credo: true
          check-format: true
          coveralls: true
          dialyzer: true
          requires: [orb-tools/publish]

      - orb-tools/increment:
          orb-path: packed/orb.yml
          orb-ref: "coletiv/elixir"
          segment: "patch"
          publish-token-variable: "$CIRCLECI_API_TOKEN"
          attach-workspace: true
          checkout: false
          requires: [elixir/build-and-test]
          filters:
            branches:
              only: master
