version: 2.1

integration-dev_filters: &integration-dev_filters
  branches:
    ignore: /.*/
  tags:
    only: /integration-.*/

integration-master_filters: &integration-master_filters
  branches:
    ignore: /.*/
  tags:
    only: /master-.*/

prod-deploy_requires: &prod-deploy_requires
  [test-orb-elixir_master]

orbs:
  orb-tools: circleci/orb-tools@8.3.0
  elixir: coletiv/elixir@dev:alpha
workflows:
  lint_pack-validate_publish-dev:
    jobs:
      - orb-tools/lint

      - orb-tools/pack:
          attach-workspace: true
          checkout: false
          source-dir: src/
          destination-orb-path: packed/orb.yml
          workspace-path: packed/orb.yml
          artifact-path: packed/orb.yml
          requires:
            - orb-tools/lint

      - orb-tools/publish-dev:
          orb-path: packed/orb.yml
          publish-token-variable: "$CIRCLECI_API_TOKEN"
          requires: [orb-tools/pack]

      - orb-tools/trigger-integration-workflow:
          name: trigger-integration-dev
          context: orb-publishing
          ssh-fingerprints: 93:72:14:95:25:37:b9:b9:34:6a:52:f0:6d:3c:8e:30
          requires:
            - orb-tools/publish-dev
          filters:
            branches:
              ignore: master

      - orb-tools/trigger-integration-workflow:
          name: trigger-integration-master
          context: orb-publishing
          ssh-fingerprints: 93:72:14:95:25:37:b9:b9:34:6a:52:f0:6d:3c:8e:30
          tag: master
          requires:
            - orb-tools/publish-dev
          filters:
            branches:
              only: master

  integration-tests_prod-deploy:
    jobs:
      - elixir/build-and-test:
          credo: true
          check-format: true
          coveralls: true
          dialyzer: true
          name: test-orb-elixir_dev
          filters: *integration-dev_filters

      - elixir/build-and-test:
          credo: true
          check-format: true
          coveralls: true
          dialyzer: true
          name: test-orb-elixir_master
          filters: *integration-master_filters

      # patch, minor, or major publishing
      - orb-tools/dev-promote-prod:
          name: dev-promote-patch
          orb-name: coletiv/elixir
          requires: *prod-deploy_requires
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /master-patch.*/

      - orb-tools/dev-promote-prod:
          name: dev-promote-minor
          orb-name: coletiv/elixir
          release: minor
          requires: *prod-deploy_requires
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /master-minor.*/

      - orb-tools/dev-promote-prod:
          name: dev-promote-major
          orb-name: coletiv/elixir
          release: major
          requires: *prod-deploy_requires
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /master-major.*/
