description: |
  Linux image with necessary tools to compile elixir code.
parameters:
  # https://hub.docker.com/r/circleci/elixir/tags/
  elixir-version:
    type: string
    default: 1.7.3
  postgres-version:
    type: string
    default: 10.1-alpine
docker:
  # https://hub.docker.com/r/circleci/postgres/tags/
  - image: circleci/elixir:<< parameters.elixir-version >>
    environment:
      MIX_ENV: test
  - image: circleci/postgres:<< parameters.postgres-version >>
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: app_test
      POSTGRES_PASSWORD:
